version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: quiz-generator-backend
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=your-secret-key-change-in-production
      - DATABASE_URL=sqlite:///./db.sqlite
    volumes:
      - backend_data:/app/instance
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: quiz-generator-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data: