services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz-generator-backend
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=your-secret-key-change-in-production
      - DATABASE_URL=sqlite:///./db.sqlite
    volumes:
      - backend_data:/app/instance
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: node:18-alpine
    container_name: quiz-generator-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    command: >
      sh -c "npm install && npm run dev"
    restart: unless-stopped

volumes:
  backend_data:
